Feature/register drugs #2
ronerjr/afrodev-team3 pull request #12
Opened 2021-04-22 23:13 UTC by Lucas96Sousa

2021-04-23 14:13 UTC, dmeneguin requested changes

2021-04-23 14:37 UTC, Lucas96Sousa commented on __tests__/drug.test.js
> +
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on __tests__/drug.test.js
> +
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on adapters/api/routes/drug.js
> +    /*#swagger.parameters['post drug object'] = {
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on adapters/api/routes/drug.js
> +    /*#swagger.parameters['put drug object'] = {
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on adapters/api/routes/drug.js
> +    if (errors.lenght > 0) {
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on adapters/api/routes/drug.js
> +    /*#swagger.parameters['patch drug object'] = {
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on adapters/api/routes/drug.js
> +    if (errors.lenght > 0) {
Corrigido

2021-04-23 14:37 UTC, Lucas96Sousa commented on config/database.config.js
> +  password: process.env.MYSQL_PASSWORD || 'admin' ,
Corrigido

2021-04-24 11:45 UTC, dmeneguin approved these changes

2021-04-24 12:21 UTC, ronerjr requested changes

2021-04-24 14:36 UTC, dmeneguin approved these changes

2021-04-24 16:44 UTC, ronerjr approved these changes

2021-04-24 16:44 UTC, merged